import requests
import json
students_data = [
    {"student_id": "21241A6701", "name": "ABBAGONI ROHITH GOUD", "email": "", "branch": "CSDS", "academic_year": 3},
    {"student_id": "21241A6702", "name": "ADUPA PARDHU", "email": "", "branch": "CSDS", "academic_year": 3},
    {"student_id": "21241A6703", "name": "ALLAM KARTHIK KUMAR", "email": "", "branch": "CSDS", "academic_year": 3},
    {"student_id": "21241A6704", "name": "ANUPATI SHIVANI", "email": "", "branch": "CSDS", "academic_year": 3},
    {"student_id": "21241A6705", "name": "AVULA ABHIRAM YADAV", "email": "", "branch": "CSDS", "academic_year": 3},
    {"student_id": "21241A6706", "name": "B SAI GANESH", "email": "", "branch": "CSDS", "academic_year": 3},
    {"student_id": "21241A6707", "name": "BALLA AVINASH MALLESH", "email": "", "branch": "CSDS", "academic_year": 3},
    {"student_id": "21241A6708", "name": "BANDARU GEETANJALI", "email": "", "branch": "CSDS", "academic_year": 3},
    {"student_id": "21241A6709", "name": "BASWA TARUN", "email": "", "branch": "CSDS", "academic_year": 3},
    {"student_id": "21241A6710", "name": "BATTULA SRAVANI", "email": "", "branch": "CSDS", "academic_year": 3},
    {"student_id": "21241A6711", "name": "BHUMIREDDY CHANDAN REDDY", "email": "", "branch": "CSDS", "academic_year": 3},
    {"student_id": "21241A6712", "name": "BODA PRAVEEN", "email": "", "branch": "CSDS", "academic_year": 3},
    {"student_id": "21241A6713", "name": "BOKKA DURGA SRI HARSHITHA", "email": "", "branch": "CSDS", "academic_year": 3},
    {"student_id": "21241A6714", "name": "BOMBOTHULA SANNITH GOUD", "email": "", "branch": "CSDS", "academic_year": 3},
    {"student_id": "21241A6715", "name": "CHERLA SRISAI KRISHNA", "email": "", "branch": "CSDS", "academic_year": 3},
    {"student_id": "21241A6716", "name": "CHERUVU VAMSIKA GAYATHRI", "email": "", "branch": "CSDS", "academic_year": 3},
    {"student_id": "21241A6717", "name": "CHINTAKINDI SANDEEP KUMAR", "email": "", "branch": "CSDS", "academic_year": 3},
    {"student_id": "21241A6718", "name": "G PRANAVI", "email": "", "branch": "CSDS", "academic_year": 3},
    {"student_id": "21241A6719", "name": "GANGAVARAPU VENKATA SRIJAN REDDY", "email": "", "branch": "CSDS", "academic_year": 3},
    {"student_id": "21241A6720", "name": "GOLI SAI CHANDANA", "email": "", "branch": "CSDS", "academic_year": 3},
    {"student_id": "21241A6721", "name": "JUTTU VARSHITH TEJA", "email": "", "branch": "CSDS", "academic_year": 3},
    {"student_id": "21241A6722", "name": "K SHYAM SUNDER RAO", "email": "", "branch": "CSDS", "academic_year": 3},
    {"student_id": "21241A6723", "name": "KAIRAMKONDA UDAY KIRAN", "email": "", "branch": "CSDS", "academic_year": 3},
    {"student_id": "21241A6724", "name": "KALVA PRANEETH", "email": "", "branch": "CSDS", "academic_year": 3},
    {"student_id": "21241A6725", "name": "KANAPALA PRIYADARSHINI", "email": "", "branch": "CSDS", "academic_year": 3},
    {"student_id": "21241A6726", "name": "KARISHA MOUNIKA", "email": "", "branch": "CSDS", "academic_year": 3},
    {"student_id": "21241A6727", "name": "M A ZUNAID ARBAAZ", "email": "", "branch": "CSDS", "academic_year": 3},
    {"student_id": "21241A6728", "name": "M TARUN RAIDU", "email": "", "branch": "CSDS", "academic_year": 3},
    {"student_id": "21241A6729", "name": "MACHANNAGARI RUPALI REDDY", "email": "", "branch": "CSDS", "academic_year": 3},
    {"student_id": "21241A6730", "name": "MADDI VAISHNAVI", "email": "", "branch": "CSDS", "academic_year": 3},
    {"student_id": "21241A6731", "name": "MADIREDDY SRI VAISHNAVI SAMHITA", "email": "", "branch": "CSDS", "academic_year": 3},
    {"student_id": "21241A6732", "name": "MAILARAM SHRUTHI", "email": "", "branch": "CSDS", "academic_year": 3},
    {"student_id": "21241A6733", "name": "MAJJI SIMHADRI", "email": "", "branch": "CSDS", "academic_year": 3},
    {"student_id": "21241A6734", "name": "MOHAMMED NAVEED ALI", "email": "", "branch": "CSDS", "academic_year": 3},
    {"student_id": "21241A6735", "name": "MUNEENDRA", "email": "", "branch": "CSDS", "academic_year": 3},
    {"student_id": "21241A6736", "name": "N ANKITH KUMAR", "email": "", "branch": "CSDS", "academic_year": 3},
    {"student_id": "21241A6737", "name": "NAGULA NAVYA SRI", "email": "", "branch": "CSDS", "academic_year": 3},
    {"student_id": "21241A6738", "name": "NARAKANTI MAHESH", "email": "", "branch": "CSDS", "academic_year": 3},
    {"student_id": "21241A6739", "name": "NYALAPATLA VAISHNAVI", "email": "", "branch": "CSDS", "academic_year": 3},
    {"student_id": "21241A6740", "name": "PADAKANDLA N V SAI KRISHNA", "email": "", "branch": "CSDS", "academic_year": 3},
    {"student_id": "21241A6741", "name": "PAIDI GOUTHAMI", "email": "", "branch": "CSDS", "academic_year": 3},
    {"student_id": "21241A6742", "name": "PAMULAPARTHY SOWMYA", "email": "", "branch": "CSDS", "academic_year": 3},
    {"student_id": "21241A6743", "name": "PHANNI SAI DASARI", "email": "", "branch": "CSDS", "academic_year": 3},
    {"student_id": "21241A6744", "name": "PITTALA VENKATA NIKITH VARMA", "email": "", "branch": "CSDS", "academic_year": 3},
    {"student_id": "21241A6745", "name": "SANKALA VARALAKASHMI", "email": "", "branch": "CSDS", "academic_year": 3},
    {"student_id": "21241A6746", "name": "PONNAPU REDDY CHENNA KESAVA REDDY", "email": "", "branch": "CSDS", "academic_year": 3},
    {"student_id": "21241A6747", "name": "POSIKA SARAN SRI BHARGAV", "email": "", "branch": "CSDS", "academic_year": 3},
    {"student_id": "21241A6748", "name": "R SAI DEVA HARSHA", "email": "", "branch": "CSDS", "academic_year": 3},
    {"student_id": "21241A6749", "name": "RETNENI SAI SUDHAMSH", "email": "", "branch": "CSDS", "academic_year": 3},
    {"student_id": "21241A6750", "name": "SAI KRISHNA GODEPALLY", "email": "", "branch": "CSDS", "academic_year": 3},
    {"student_id": "21241A6751", "name": "SAMALA SAI VIVEK", "email": "", "branch": "CSDS", "academic_year": 3},
    {"student_id": "21241A6752", "name": "SHAIK NAZIR HUSSAIN", "email": "", "branch": "CSDS", "academic_year": 3},
    {"student_id": "21241A6753", "name": "SHAIK SHAMEEM", "email": "", "branch": "CSDS", "academic_year": 3},
    {"student_id": "21241A6754", "name": "SHIVAM MANDAL", "email": "", "branch": "CSDS", "academic_year": 3},
    {"student_id": "21241A6755", "name": "SWETHA S", "email": "", "branch": "CSDS", "academic_year": 3},
    {"student_id": "21241A6756", "name": "TAMMINEEDI NAGA SAI TANUSRI", "email": "", "branch": "CSDS", "academic_year": 3},
    {"student_id": "21241A6757", "name": "THIMMAREDDY GARI VINAYAK REDDY", "email": "", "branch": "CSDS", "academic_year": 3},
    {"student_id": "21241A6758", "name": "THRISHA VARMA SRIMANDAPATI", "email": "", "branch": "CSDS", "academic_year": 3},
    {"student_id": "21241A6759", "name": "TIRUKUTCHU MODHITA", "email": "", "branch": "CSDS", "academic_year": 3},
    {"student_id": "21241A6760", "name": "TIRUMANI PRANAYA", "email": "", "branch": "CSDS", "academic_year": 3},
    {"student_id": "21241A6761", "name": "ULLI PRIYANKA RAO", "email": "", "branch": "CSDS", "academic_year": 3},
    {"student_id": "21241A6762", "name": "URLANA KISHOR", "email": "", "branch": "CSDS", "academic_year": 3},
    {"student_id": "21241A6763", "name": "VIVEK GAJAWADA", "email": "", "branch": "CSDS", "academic_year": 3},
    {"student_id": "21241A6764", "name": "VUDARA VIVEK CHANDRA", "email": "", "branch": "CSDS", "academic_year": 3},
    {"student_id": "21241A6765", "name": "YARLAGADDA SESHA SAI VIVEK", "email": "", "branch": "CSDS", "academic_year": 3},
    {"student_id": "22245A6701", "name": "BETHI ANUHYA", "email": "", "branch": "CSDS", "academic_year": 3},
    {"student_id": "22245A6702", "name": "BUSSA SAI KIRAN", "email": "", "branch": "CSDS", "academic_year": 3},
    {"student_id": "22245A6703", "name": "GOPALPUTTIPOOJA", "email": "", "branch": "CSDS", "academic_year": 3},
    {"student_id": "22245A6704", "name": "PEDDOJU MADHULITHA", "email": "", "branch": "CSDS", "academic_year": 3},
    {"student_id": "22245A6705", "name": "PULI KALPANA", "email": "", "branch": "CSDS", "academic_year": 3},
    {"student_id": "22245A6706", "name": "VADDE NAVEEN", "email": "", "branch": "CSDS", "academic_year": 3}
]

for student in students_data:
    headers = {'Content-Type': 'application/json'}
    response = requests.post('http://127.0.0.1:5000/create_student', headers=headers, json=student)
    print(response.json())